
DROP TABLE COMPROBANTE IF EXISTS;

CREATE TABLE COMPROBANTE (
comprobanteId INT NOT NULL AUTO_INCREMENT,
clienteId INT NOT NULL,
total INT,
fecha DATE,
CONSTRAINT FK_cliente FOREIGN KEY (clienteid)
REFERENCES cliente(clienteId)
);


DROP TABLE VENTA IF EXISTS;

CREATE TABLE VENTA (
ventaId INT NOT NULL AUTO_INCREMENT,
comprobanteId INT NOT NULL,
productoId INT NOT NULL,
cantidad INT,
total INT,
CONSTRAINT FK_comprobante FOREIGN KEY (comprobanteId)
REFERENCES comprobante(comprobanteId),
CONSTRAINT FK_producto FOREIGN KEY (productoId)
REFERENCES producto(productoId)
);


DROP TABLE CLIENTE IF EXISTS;

CREATE TABLE CLIENTE (
clienteId INT NOT NULL AUTO_INCREMENT,
nombre VARCHAR(100),
apellido VARCHAR(100),
dni INT,
PRIMARY KEY (clienteId)
);


DROP TABLE PRODUCTO IF EXISTS;

CREATE TABLE PRODUCTO (
productoId INT NOT NULL AUTO_INCREMENT,
descripcion VARCHAR(100),
precio INT,
stock INT,
PRIMARY KEY (productoId)
);


