DROP TABLE CLIENTE IF EXISTS;

CREATE TABLE CLIENTE (
clienteId INT NOT NULL AUTO_INCREMENT,
nombre VARCHAR(100),
apellido VARCHAR(100),
dni INT,
PRIMARY KEY (clienteId)
);


DROP TABLE PRODUCTO IF EXISTS;

CREATE TABLE PRODUCTO (
productoId INT NOT NULL AUTO_INCREMENT,
descripcion VARCHAR(100),
precio INT,
cantidad INT,
PRIMARY KEY (productoId)
);